import type { LanguageCode } from "./languages";

export type SignCategory =
  | "greetings"
  | "daily"
  | "medical"
  | "travel"
  | "education"
  | "emergency";

export const CATEGORY_LABELS: Record<SignCategory, string> = {
  greetings: "Greetings",
  daily: "Daily life",
  medical: "Medical",
  travel: "Travel",
  education: "Education",
  emergency: "Emergency",
};

export interface SignEntry {
  id: string;
  /** English gloss token used by the recognizer/model label map. */
  label: string;
  /** Sentence-level meaning the pipeline outputs, not just the handshape. */
  meaning: string;
  category: SignCategory;
  /** true when the sign requires motion over time (LSTM/GRU window). */
  dynamic: boolean;
  twoHanded: boolean;
  facialCue?: string;
  steps: string[];
  translations: Record<Exclude<LanguageCode, "en">, string>;
}

type T = SignEntry["translations"];

const t = (
  hi: string,
  kn: string,
  te: string,
  ta: string,
  ml: string,
  mr: string,
  bn: string,
  gu: string,
  pa: string,
): T => ({ hi, kn, te, ta, ml, mr, bn, gu, pa });

export const VOCABULARY: SignEntry[] = [
  {
    id: "hello",
    label: "HELLO",
    meaning: "Hello",
    category: "greetings",
    dynamic: true,
    twoHanded: false,
    facialCue: "Friendly smile, raised eyebrows",
    steps: [
      "Open your dominant hand with fingers together.",
      "Bring your palm near your forehead.",
      "Move the hand outward and away in a small arc.",
    ],
    translations: t(
      "नमस्ते",
      "ನಮಸ್ಕಾರ",
      "నమస్కారం",
      "வணக்கம்",
      "നമസ്കാരം",
      "नमस्कार",
      "নমস্কার",
      "નમસ્તે",
      "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
    ),
  },
  {
    id: "thank-you",
    label: "THANK_YOU",
    meaning: "Thank you",
    category: "greetings",
    dynamic: true,
    twoHanded: false,
    steps: [
      "Place your flat hand near your chin, palm facing you.",
      "Move the hand forward and slightly down toward the other person.",
    ],
    translations: t(
      "धन्यवाद",
      "ಧನ್ಯವಾದ",
      "ధన్యవాదాలు",
      "நன்றி",
      "നന്ദി",
      "धन्यवाद",
      "ধন্যবাদ",
      "આભાર",
      "ਧੰਨਵਾਦ",
    ),
  },
  {
    id: "yes",
    label: "YES",
    meaning: "Yes",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    facialCue: "Nod along with the sign",
    steps: ["Make a fist.", "Nod the fist up and down from the wrist."],
    translations: t("हाँ", "ಹೌದು", "అవును", "ஆம்", "അതെ", "होय", "হ্যাঁ", "હા", "ਹਾਂ"),
  },
  {
    id: "no",
    label: "NO",
    meaning: "No",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    facialCue: "Small head shake",
    steps: [
      "Extend index and middle finger with the thumb.",
      "Tap the two fingers to the thumb once, firmly.",
    ],
    translations: t("नहीं", "ಇಲ್ಲ", "కాదు", "இல்லை", "ഇല്ല", "नाही", "না", "ના", "ਨਹੀਂ"),
  },
  {
    id: "please",
    label: "PLEASE",
    meaning: "Please",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    steps: ["Place your open palm on your chest.", "Move it in a slow circle."],
    translations: t(
      "कृपया",
      "ದಯವಿಟ್ಟು",
      "దయచేసి",
      "தயவுசெய்து",
      "ദയവായി",
      "कृपया",
      "অনুগ্রহ করে",
      "કૃપા કરીને",
      "ਕਿਰਪਾ ਕਰਕੇ",
    ),
  },
  {
    id: "sorry",
    label: "SORRY",
    meaning: "Sorry",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    facialCue: "Apologetic expression",
    steps: ["Make a fist with the thumb outside.", "Rub it in a circle over your chest."],
    translations: t(
      "माफ़ कीजिए",
      "ಕ್ಷಮಿಸಿ",
      "క్షమించండి",
      "மன்னிக்கவும்",
      "ക്ഷമിക്കണം",
      "माफ करा",
      "দুঃখিত",
      "માફ કરશો",
      "ਮਾਫ਼ ਕਰਨਾ",
    ),
  },
  {
    id: "help",
    label: "HELP",
    meaning: "I need help",
    category: "emergency",
    dynamic: true,
    twoHanded: true,
    facialCue: "Urgent, concerned expression",
    steps: [
      "Make a fist with the thumb up on one hand.",
      "Rest that fist on your other flat palm.",
      "Lift both hands upward together.",
    ],
    translations: t(
      "मुझे मदद चाहिए",
      "ನನಗೆ ಸಹಾಯ ಬೇಕು",
      "నాకు సహాయం కావాలి",
      "எனக்கு உதவி வேண்டும்",
      "എനിക്ക് സഹായം വേണം",
      "मला मदत हवी आहे",
      "আমার সাহায্য দরকার",
      "મને મદદ જોઈએ છે",
      "ਮੈਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ",
    ),
  },
  {
    id: "water",
    label: "WATER",
    meaning: "I need water",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    steps: [
      "Extend three fingers to form the 'W' handshape.",
      "Tap the index finger against your chin twice.",
    ],
    translations: t(
      "मुझे पानी चाहिए",
      "ನನಗೆ ನೀರು ಬೇಕು",
      "నాకు నీళ్లు కావాలి",
      "எனக்கு தண்ணீர் வேண்டும்",
      "എനിക്ക് വെള്ളം വേണം",
      "मला पाणी हवे आहे",
      "আমার পানি দরকার",
      "મને પાણી જોઈએ છે",
      "ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ",
    ),
  },
  {
    id: "food",
    label: "FOOD",
    meaning: "I am hungry",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    steps: [
      "Bring your fingertips together as if holding food.",
      "Move the hand toward your mouth twice.",
    ],
    translations: t(
      "मुझे भूख लगी है",
      "ನನಗೆ ಹಸಿವಾಗಿದೆ",
      "నాకు ఆకలిగా ఉంది",
      "எனக்கு பசிக்கிறது",
      "എനിക്ക് വിശക്കുന്നു",
      "मला भूक लागली आहे",
      "আমার খিদে পেয়েছে",
      "મને ભૂખ લાગી છે",
      "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ",
    ),
  },
  {
    id: "hospital",
    label: "HOSPITAL",
    meaning: "Take me to the hospital",
    category: "medical",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Extend index and middle fingers of the dominant hand.",
      "Draw a cross shape on your opposite upper arm.",
    ],
    translations: t(
      "मुझे अस्पताल ले चलिए",
      "ನನ್ನನ್ನು ಆಸ್ಪತ್ರೆಗೆ ಕರೆದೊಯ್ಯಿರಿ",
      "నన్ను ఆసుపత్రికి తీసుకెళ్లండి",
      "என்னை மருத்துவமனைக்கு அழைத்துச் செல்லுங்கள்",
      "എന്നെ ആശുപത്രിയിൽ കൊണ്ടുപോകൂ",
      "मला रुग्णालयात न्या",
      "আমাকে হাসপাতালে নিয়ে চলুন",
      "મને હોસ્પિટલ લઈ જાઓ",
      "ਮੈਨੂੰ ਹਸਪਤਾਲ ਲੈ ਚੱਲੋ",
    ),
  },
  {
    id: "doctor",
    label: "DOCTOR",
    meaning: "I need a doctor",
    category: "medical",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Hold one wrist with the fingers of the other hand, as if checking a pulse.",
      "Tap twice on the wrist.",
    ],
    translations: t(
      "मुझे डॉक्टर चाहिए",
      "ನನಗೆ ವೈದ್ಯರು ಬೇಕು",
      "నాకు డాక్టర్ కావాలి",
      "எனக்கு மருத்துவர் வேண்டும்",
      "എനിക്ക് ഡോക്ടറെ വേണം",
      "मला डॉक्टर हवे आहेत",
      "আমার ডাক্তার দরকার",
      "મને ડૉક્ટરની જરૂર છે",
      "ਮੈਨੂੰ ਡਾਕਟਰ ਚਾਹੀਦਾ ਹੈ",
    ),
  },
  {
    id: "medicine",
    label: "MEDICINE",
    meaning: "I need medicine",
    category: "medical",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Open one palm flat.",
      "Touch the middle finger of the other hand into the palm and rock it side to side.",
    ],
    translations: t(
      "मुझे दवा चाहिए",
      "ನನಗೆ ಔಷಧಿ ಬೇಕು",
      "నాకు మందు కావాలి",
      "எனக்கு மருந்து வேண்டும்",
      "എനിക്ക് മരുന്ന് വേണം",
      "मला औषध हवे आहे",
      "আমার ওষুধ দরকার",
      "મને દવા જોઈએ છે",
      "ਮੈਨੂੰ ਦਵਾਈ ਚਾਹੀਦੀ ਹੈ",
    ),
  },
  {
    id: "pain",
    label: "PAIN",
    meaning: "I am in pain",
    category: "medical",
    dynamic: true,
    twoHanded: true,
    facialCue: "Tense expression — the face carries the intensity",
    steps: [
      "Point both index fingers toward each other.",
      "Twist them back and forth near the area that hurts.",
    ],
    translations: t(
      "मुझे दर्द हो रहा है",
      "ನನಗೆ ನೋವಾಗುತ್ತಿದೆ",
      "నాకు నొప్పిగా ఉంది",
      "எனக்கு வலிக்கிறது",
      "എനിക്ക് വേദനയുണ്ട്",
      "मला वेदना होत आहेत",
      "আমার ব্যথা করছে",
      "મને દુખાવો થાય છે",
      "ਮੈਨੂੰ ਦਰਦ ਹੋ ਰਿਹਾ ਹੈ",
    ),
  },
  {
    id: "home",
    label: "HOME",
    meaning: "I want to go home",
    category: "daily",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Join both hands above your head to form a roof shape.",
      "Lower them to outline the walls of a house.",
    ],
    translations: t(
      "मुझे घर जाना है",
      "ನನಗೆ ಮನೆಗೆ ಹೋಗಬೇಕು",
      "నేను ఇంటికి వెళ్లాలి",
      "நான் வீட்டுக்கு போக வேண்டும்",
      "എനിക്ക് വീട്ടിൽ പോകണം",
      "मला घरी जायचे आहे",
      "আমি বাড়ি যেতে চাই",
      "મારે ઘરે જવું છે",
      "ਮੈਂ ਘਰ ਜਾਣਾ ਚਾਹੁੰਦਾ ਹਾਂ",
    ),
  },
  {
    id: "family",
    label: "FAMILY",
    meaning: "Call my family",
    category: "emergency",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Hold both hands in front of you with fingertips together.",
      "Draw a circle outward and bring the hands back together.",
    ],
    translations: t(
      "मेरे परिवार को बुलाइए",
      "ನನ್ನ ಕುಟುಂಬಕ್ಕೆ ಕರೆ ಮಾಡಿ",
      "నా కుటుంబానికి కాల్ చేయండి",
      "என் குடும்பத்தை அழைக்கவும்",
      "എന്റെ കുടുംബത്തെ വിളിക്കൂ",
      "माझ्या कुटुंबाला बोलवा",
      "আমার পরিবারকে ফোন করুন",
      "મારા પરિવારને બોલાવો",
      "ਮੇਰੇ ਪਰਿਵਾਰ ਨੂੰ ਬੁਲਾਓ",
    ),
  },
  {
    id: "friend",
    label: "FRIEND",
    meaning: "This is my friend",
    category: "daily",
    dynamic: true,
    twoHanded: true,
    steps: ["Hook both index fingers together.", "Release and hook them the other way."],
    translations: t(
      "यह मेरा दोस्त है",
      "ಇವರು ನನ್ನ ಸ್ನೇಹಿತ",
      "ఇతను నా స్నేహితుడు",
      "இவர் என் நண்பர்",
      "ഇത് എന്റെ സുഹൃത്താണ്",
      "हा माझा मित्र आहे",
      "এ আমার বন্ধু",
      "આ મારો મિત્ર છે",
      "ਇਹ ਮੇਰਾ ਦੋਸਤ ਹੈ",
    ),
  },
  {
    id: "your-name",
    label: "YOUR_NAME",
    meaning: "What is your name?",
    category: "greetings",
    dynamic: true,
    twoHanded: true,
    facialCue: "Raised eyebrows mark the question",
    steps: [
      "Tap the two extended fingers of both hands together twice.",
      "Point toward the other person.",
    ],
    translations: t(
      "आपका नाम क्या है?",
      "ನಿಮ್ಮ ಹೆಸರೇನು?",
      "మీ పేరు ఏమిటి?",
      "உங்கள் பெயர் என்ன?",
      "നിങ്ങളുടെ പേരെന്താണ്?",
      "तुमचे नाव काय आहे?",
      "আপনার নাম কী?",
      "તમારું નામ શું છે?",
      "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ?",
    ),
  },
  {
    id: "my-name",
    label: "MY_NAME",
    meaning: "My name is …",
    category: "greetings",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Point to yourself.",
      "Tap the two extended fingers of both hands together twice.",
      "Fingerspell your name.",
    ],
    translations: t(
      "मेरा नाम … है",
      "ನನ್ನ ಹೆಸರು …",
      "నా పేరు …",
      "என் பெயர் …",
      "എന്റെ പേര് …",
      "माझे नाव … आहे",
      "আমার নাম …",
      "મારું નામ … છે",
      "ਮੇਰਾ ਨਾਮ … ਹੈ",
    ),
  },
  {
    id: "how-are-you",
    label: "HOW_ARE_YOU",
    meaning: "How are you?",
    category: "greetings",
    dynamic: true,
    twoHanded: true,
    facialCue: "Raised eyebrows, slight head tilt",
    steps: [
      "Place both curved hands together, knuckles touching.",
      "Roll them forward and open the palms upward.",
      "Point toward the other person.",
    ],
    translations: t(
      "आप कैसे हैं?",
      "ನೀವು ಹೇಗಿದ್ದೀರಿ?",
      "మీరు ఎలా ఉన్నారు?",
      "நீங்கள் எப்படி இருக்கிறீர்கள்?",
      "സുഖമാണോ?",
      "तुम्ही कसे आहात?",
      "আপনি কেমন আছেন?",
      "તમે કેમ છો?",
      "ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?",
    ),
  },
  {
    id: "fine",
    label: "FINE",
    meaning: "I am fine",
    category: "greetings",
    dynamic: true,
    twoHanded: false,
    facialCue: "Relaxed, positive expression",
    steps: ["Touch your thumb to your chest with the hand open.", "Move the hand forward."],
    translations: t(
      "मैं ठीक हूँ",
      "ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ",
      "నేను బాగున్నాను",
      "நான் நலமாக இருக்கிறேன்",
      "എനിക്ക് സുഖമാണ്",
      "मी ठीक आहे",
      "আমি ভালো আছি",
      "હું ઠીક છું",
      "ਮੈਂ ਠੀਕ ਹਾਂ",
    ),
  },
  {
    id: "police",
    label: "POLICE",
    meaning: "Call the police",
    category: "emergency",
    dynamic: true,
    twoHanded: false,
    steps: [
      "Form a 'C' shape with the dominant hand.",
      "Tap it twice against the opposite shoulder, like a badge.",
    ],
    translations: t(
      "पुलिस को बुलाइए",
      "ಪೊಲೀಸರನ್ನು ಕರೆಯಿರಿ",
      "పోలీసులను పిలవండి",
      "போலீசை அழைக்கவும்",
      "പോലീസിനെ വിളിക്കൂ",
      "पोलिसांना बोलवा",
      "পুলিশ ডাকুন",
      "પોલીસને બોલાવો",
      "ਪੁਲਿਸ ਨੂੰ ਬੁਲਾਓ",
    ),
  },
  {
    id: "ambulance",
    label: "AMBULANCE",
    meaning: "Call an ambulance",
    category: "emergency",
    dynamic: true,
    twoHanded: true,
    facialCue: "Urgent expression",
    steps: [
      "Sign HOSPITAL with a cross on the upper arm.",
      "Then rotate an open hand above your head like a siren light.",
    ],
    translations: t(
      "एम्बुलेंस बुलाइए",
      "ಆಂಬ್ಯುಲೆನ್ಸ್ ಕರೆಯಿರಿ",
      "అంబులెన్స్ పిలవండి",
      "ஆம்புலன்ஸ் அழைக்கவும்",
      "ആംബുലൻസ് വിളിക്കൂ",
      "रुग्णवाहिका बोलवा",
      "অ্যাম্বুলেন্স ডাকুন",
      "એમ્બ્યુલન્સ બોલાવો",
      "ਐਂਬੂਲੈਂਸ ਬੁਲਾਓ",
    ),
  },
  {
    id: "lost",
    label: "LOST",
    meaning: "I am lost",
    category: "emergency",
    dynamic: true,
    twoHanded: true,
    facialCue: "Worried expression",
    steps: [
      "Point to yourself.",
      "Move both open hands apart in an uncertain, searching motion.",
    ],
    translations: t(
      "मैं रास्ता भटक गया हूँ",
      "ನಾನು ದಾರಿ ತಪ್ಪಿದ್ದೇನೆ",
      "నేను దారి తప్పాను",
      "நான் வழி தவறிவிட்டேன்",
      "എനിക്ക് വഴി തെറ്റി",
      "मी हरवलो आहे",
      "আমি পথ হারিয়েছি",
      "હું રસ્તો ભૂલી ગયો છું",
      "ਮੈਂ ਰਾਹ ਭੁੱਲ ਗਿਆ ਹਾਂ",
    ),
  },
  {
    id: "injured",
    label: "INJURED",
    meaning: "I am injured",
    category: "emergency",
    dynamic: true,
    twoHanded: true,
    facialCue: "Pained expression",
    steps: [
      "Point to yourself.",
      "Sign PAIN near the injured body part with both index fingers.",
    ],
    translations: t(
      "मुझे चोट लगी है",
      "ನನಗೆ ಗಾಯವಾಗಿದೆ",
      "నాకు గాయమైంది",
      "எனக்கு காயம் ஏற்பட்டுள்ளது",
      "എനിക്ക് പരിക്കുണ്ട്",
      "मला दुखापत झाली आहे",
      "আমি আহত হয়েছি",
      "મને ઈજા થઈ છે",
      "ਮੈਨੂੰ ਸੱਟ ਲੱਗੀ ਹੈ",
    ),
  },
  {
    id: "wait",
    label: "WAIT",
    meaning: "Please wait",
    category: "daily",
    dynamic: true,
    twoHanded: true,
    steps: [
      "Hold both hands up, palms facing up, fingers spread.",
      "Wiggle the fingers gently.",
    ],
    translations: t(
      "कृपया प्रतीक्षा करें",
      "ದಯವಿಟ್ಟು ಕಾಯಿರಿ",
      "దయచేసి వేచి ఉండండి",
      "தயவுசெய்து காத்திருங்கள்",
      "ദയവായി കാത്തിരിക്കൂ",
      "कृपया थांबा",
      "অনুগ্রহ করে অপেক্ষা করুন",
      "કૃપા કરીને રાહ જુઓ",
      "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ",
    ),
  },
  {
    id: "understand",
    label: "UNDERSTAND",
    meaning: "I understand",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    facialCue: "Nod to confirm",
    steps: [
      "Hold a closed fist near your forehead.",
      "Flick the index finger up once.",
    ],
    translations: t(
      "मैं समझ गया",
      "ನನಗೆ ಅರ್ಥವಾಯಿತು",
      "నాకు అర్థమైంది",
      "எனக்கு புரிகிறது",
      "എനിക്ക് മനസ്സിലായി",
      "मला समजले",
      "আমি বুঝেছি",
      "મને સમજાયું",
      "ਮੈਨੂੰ ਸਮਝ ਆ ਗਿਆ",
    ),
  },
  {
    id: "not-understand",
    label: "NOT_UNDERSTAND",
    meaning: "I do not understand",
    category: "daily",
    dynamic: true,
    twoHanded: false,
    facialCue: "Furrowed brows, small head shake",
    steps: [
      "Sign UNDERSTAND near the forehead.",
      "Shake your head while the hand stays closed.",
    ],
    translations: t(
      "मैं नहीं समझा",
      "ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ",
      "నాకు అర్థం కాలేదు",
      "எனக்கு புரியவில்லை",
      "എനിക്ക് മനസ്സിലായില്ല",
      "मला समजले नाही",
      "আমি বুঝিনি",
      "મને સમજાયું નહીં",
      "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਇਆ",
    ),
  },
  {
    id: "school",
    label: "SCHOOL",
    meaning: "I go to school",
    category: "education",
    dynamic: true,
    twoHanded: true,
    steps: ["Clap your open palms together twice.", "Then point forward and away."],
    translations: t(
      "मैं स्कूल जाता हूँ",
      "ನಾನು ಶಾಲೆಗೆ ಹೋಗುತ್ತೇನೆ",
      "నేను పాఠశాలకు వెళ్తాను",
      "நான் பள்ளிக்கு செல்கிறேன்",
      "ഞാൻ സ്കൂളിൽ പോകുന്നു",
      "मी शाळेत जातो",
      "আমি স্কুলে যাই",
      "હું શાળાએ જાઉં છું",
      "ਮੈਂ ਸਕੂਲ ਜਾਂਦਾ ਹਾਂ",
    ),
  },
  {
    id: "cost",
    label: "COST",
    meaning: "How much does it cost?",
    category: "travel",
    dynamic: true,
    twoHanded: true,
    facialCue: "Raised eyebrows for the question",
    steps: [
      "Rub the thumb across the fingertips (the money sign).",
      "Turn both palms upward to ask the question.",
    ],
    translations: t(
      "इसकी कीमत क्या है?",
      "ಇದರ ಬೆಲೆ ಎಷ್ಟು?",
      "దీని ధర ఎంత?",
      "இதன் விலை என்ன?",
      "ഇതിന്റെ വില എത്രയാണ്?",
      "याची किंमत किती आहे?",
      "এর দাম কত?",
      "આની કિંમત કેટલી છે?",
      "ਇਸ ਦੀ ਕੀਮਤ ਕੀ ਹੈ?",
    ),
  },
  {
    id: "bus-stop",
    label: "BUS_STOP",
    meaning: "Where is the bus stop?",
    category: "travel",
    dynamic: true,
    twoHanded: true,
    facialCue: "Raised eyebrows for the question",
    steps: [
      "Sign BUS by outlining a vehicle shape with both hands.",
      "Shake an upright index finger side to side to ask 'where'.",
    ],
    translations: t(
      "बस स्टॉप कहाँ है?",
      "ಬಸ್ ನಿಲ್ದಾಣ ಎಲ್ಲಿದೆ?",
      "బస్ స్టాప్ ఎక్కడ ఉంది?",
      "பேருந்து நிறுத்தம் எங்கே?",
      "ബസ് സ്റ്റോപ്പ് എവിടെയാണ്?",
      "बस थांबा कुठे आहे?",
      "বাস স্টপ কোথায়?",
      "બસ સ્ટોપ ક્યાં છે?",
      "ਬੱਸ ਸਟਾਪ ਕਿੱਥੇ ਹੈ?",
    ),
  },
];

export const EMERGENCY_SIGN_IDS = [
  "help",
  "ambulance",
  "police",
  "doctor",
  "injured",
  "lost",
  "family",
  "water",
];

export function getSign(id: string): SignEntry | undefined {
  return VOCABULARY.find((s) => s.id === id);
}

export function translateMeaning(sign: SignEntry, lang: LanguageCode): string {
  if (lang === "en") return sign.meaning;
  return sign.translations[lang] ?? sign.meaning;
}